general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = notify-send "Welcome back!" && hyprctl dispatch dpms on
}

# Dim screen after 5 minutes
listener {
    timeout = 300
    on-timeout = brightnessctl set 10%
    on-resume = brightnessctl set 100%
}

# Lock screen after 10 minutes
listener {
    timeout = 600
    on-timeout = loginctl lock-session
}

# Suspend after 30 minutes (1800 seconds)
listener {
    timeout = 1500
    on-timeout = notify-send "Zzz..." "Hibernating in 5 minutes unless you move!"
}

listener {
    timeout = 1800
    on-timeout = systemctl suspend
}
